params:
  epochs: 10
  batch_size: 32
  num_classes: 10
  metrics: accuracy
  optimizer: SGD
  loss_function: sparse_categorical_crossentropy
  validation_datasize: 5000
  patience: 5
  restore_best_weights: True



artifacts:
  artifacts_dir: artifacts
  model_dir: model
  plots_dir: plots
  CHECKPOINT_DIR: checkpoints
  model_name: model.h5
  
logs:
  logs_dir: log_dir
  general_logs: general_logs
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs